package es.facite.csvdbq.qlcsv;

import es.facite.text.Scanner;

class Tokens {
	static final int ADD = 0;
	static final int SUB = 1;
	static final int MUL = 2;
	static final int DIV = 3;
	static final int MOD = 4;
	static final int POW = 5;

	static final int GT = 11;
	static final int LT = 12;
	static final int EQ = 13;
	static final int NE = 14;
	static final int GE = 15;
	static final int LE = 16;
	static final int ASIG = 17;	
	
	static final int OPEN_PARENT = 22;
	static final int CLOSED_PARENT = 23;
	static final int COMMA = 24;
	static final int SEMICOLON = 25;

	static final int TRUE = 30;
	static final int FALSE = 31;
	static final int AND = 32;
	static final int OR = 33;
	static final int NOT = 34;
	static final int TIMESTAMP = 35;
	static final int SHA = 36;	
	static final int SUBSTRING = 37;
	static final int IIF = 38;
	static final int STRING = 39;
	static final int RELIKE = 40;
	static final int COUNT = 41;
	static final int AVG = 42;
	static final int SUM = 43;
	static final int MIN = 44;
	static final int MAX = 45;
	
	static final int SELECT = 51;
	static final int FROM = 52;
	static final int WHERE = 53;
	static final int INSERT = 54;
	static final int INTO = 55;
	static final int VALUES = 56;
	static final int DELETE = 57;
	static final int UPDATE = 58;
	static final int SET = 59;
	static final int CREATE = 60;
	static final int TABLE = 61;
	static final int AS = 62;
	static final int ORDER = 63;
	static final int BY = 64;
	static final int ASC = 65;
	static final int DESC = 66;
	static final int LIMIT = 67;	
	static final int GROUP = 68;
	static final int DISTINCT = 69;
	static final int HAVING = 70;
	static final int BETWEEN = 71;
	static final int IS = 72;
	static final int NULL = 73;
	static final int SHOW = 74;
	static final int DROP = 75;
	static final int ENCRYPT = 76;
	static final int DECRYPT = 77;
	static final int TYPEOF = 78;
	static final int IN = 79;
	
	static void initialize(Scanner scan) {		
		scan.setOperatorString("'");
		scan.setOperatorRawStringBegin("@'");
		scan.setOperatorRawStringEnd("'");
		scan.setOperatorCommentEol("//");
		scan.setOperatorCommentMultilineBegin("/*");
		scan.setOperatorCommentMultilineEnd("*/");
		scan.setOperatorSpecialIdentBegin("[");
		scan.setOperatorSpecialIdentEnd("]");
		scan.setDecimalSeparatorPoint(true);
		scan.setIgnoreSpacesInLine(true);
		scan.setIgnoreEndOfLines(true);
		scan.setIgnoreComments(true);
				
		scan.operatorAdd(ADD, "+");
		scan.operatorAdd(SUB, "-");
		scan.operatorAdd(MUL, "*");
		scan.operatorAdd(DIV, "/");
		scan.operatorAdd(MOD, "%");
		scan.operatorAdd(POW, "**");
		scan.operatorAdd(POW, "^");
		scan.operatorAdd(NOT, "!");
		scan.operatorAdd(AND, "&&");
		scan.operatorAdd(OR, "||");
		scan.operatorAdd(GT, ">");
		scan.operatorAdd(LT, "<");
		scan.operatorAdd(ASIG, "=");
		scan.operatorAdd(EQ, "==");
		scan.operatorAdd(NE, "<>");
		scan.operatorAdd(NE, "!=");
		scan.operatorAdd(GE, ">=");
		scan.operatorAdd(LE, "<=");				
		scan.operatorAdd(OPEN_PARENT, "(");
		scan.operatorAdd(CLOSED_PARENT, ")");
		scan.operatorAdd(COMMA, ",");
		scan.operatorAdd(SEMICOLON, ";");

		scan.keywordAdd(TRUE, "TRUE");
		scan.keywordAdd(FALSE, "FALSE");
		scan.keywordAdd(AND, "AND");
		scan.keywordAdd(OR, "OR");
		scan.keywordAdd(NOT, "NOT");
		scan.keywordAdd(TIMESTAMP, "TIMESTAMP");
		scan.keywordAdd(SHA, "SHA");
		scan.keywordAdd(SUBSTRING, "SUBSTRING");
		scan.keywordAdd(IIF, "IIF");
		scan.keywordAdd(STRING, "STRING");
		scan.keywordAdd(RELIKE, "RELIKE");
		scan.keywordAdd(COUNT, "COUNT");
		scan.keywordAdd(AVG, "AVG");
		scan.keywordAdd(SUM, "SUM");
		scan.keywordAdd(MIN, "MIN");
		scan.keywordAdd(MAX, "MAX");		
		scan.keywordAdd(SELECT, "SELECT");
		scan.keywordAdd(FROM, "FROM");
		scan.keywordAdd(WHERE, "WHERE");
		scan.keywordAdd(INSERT, "INSERT");
		scan.keywordAdd(INTO, "INTO");
		scan.keywordAdd(VALUES, "VALUES");
		scan.keywordAdd(DELETE, "DELETE");
		scan.keywordAdd(UPDATE, "UPDATE");
		scan.keywordAdd(SET, "SET");
		scan.keywordAdd(CREATE, "CREATE");
		scan.keywordAdd(TABLE, "TABLE");
		scan.keywordAdd(AS, "AS");
		scan.keywordAdd(ORDER, "ORDER");
		scan.keywordAdd(BY, "BY");
		scan.keywordAdd(ASC, "ASC");
		scan.keywordAdd(DESC, "DESC");
		scan.keywordAdd(LIMIT, "LIMIT");		
		scan.keywordAdd(GROUP, "GROUP");
		scan.keywordAdd(DISTINCT, "DISTINCT");
		scan.keywordAdd(HAVING, "HAVING");
		scan.keywordAdd(BETWEEN, "BETWEEN");
		scan.keywordAdd(IS, "IS");
		scan.keywordAdd(NULL, "NULL");
		scan.keywordAdd(SHOW, "SHOW");
		scan.keywordAdd(DROP, "DROP");
		scan.keywordAdd(ENCRYPT, "ENCRYPT");
		scan.keywordAdd(DECRYPT, "DECRYPT");
		scan.keywordAdd(TYPEOF, "TYPEOF");
		scan.keywordAdd(IN, "IN");
	}	
}
